export const DATA_LOADER = "SET_LOADER";
export const DATA_LOADED_SUCCESSFULLY = "DATA_LOADED_SUCCESSFULLY";
export const DATA_LOADED_FAILED ="DATA_LOADED_FAILED"


export const SEARCHED_DATA = "SEARCHED_DATA";
export const SEARCHED_DATA_SUCCESSFULLY = "SEARCHED_DATA_SUCCESSFULLY";
export const SEARCHED_DATA_FAILED = "SEARCHED_DATA_FAILED";